data:
  raw_dir: data/raw
  processed_dir: data/processed
  metadata_file: data/metadata/metadata.csv

processing:
  audio:
    sample_rate: 22050
    hop_length: 512
    cqt_bins: 84
  midi:
    resolution: 100
    velocity_threshold: 20

logs:
  output_dir: src/logs
  output_filename: maestro_pipeline.log
