data:
  raw_dir: data/raw
  processed_dir: data/processed
  metadata_file: data/metadata/metadata.csv

processing:
  audio:
    sample_rate: null # keeping it null reads sr automatically from file metadata
    hop_length: 512
    cqt_bins: 288 # 288 frequencies
    bins_per_octave: 36 # 8 octaves and 36 frequencies in each octave
  midi:
    velocity_threshold: 20 # intensity of pressing key  gt this threshold is considered on & lt is off, range: (0-127)

logs:
  output_dir: src/logs
  output_filename: maestro_pipeline.log
