data:
  raw_dir: data/raw
  processed_dir: data/processed
  metadata_file: data/metadata/data.csv

processing:
  sample_rate: 22050
  hop_length: 512
  cqt_bins: 84
  midi_resolution: 100
  midi_velocity_threshold: 20

logs:
  output_dir: src/logs
